var rangos = [{
        min: 0,
        max: 20
    }, {
        min: 21,
        max: 50
    }, {
        min: 51,
        max: 75
    }, {
        min: 76,
        max: 100
    }, {
        min: 101,
        max: 150
    }, {
        min: 151,
        max: 200
    }, {
        min: 201,
        max: 250
    }, {
        min: 251,
        max: 300
    }, {
        min: 301,
        max: 400
    }, {
        min: 401,
        max: 500
    }, {
        min: 501,
        max: 600
    }, {
        min: 601,
        max: 700
    }, {
        min: 701,
        max: 800
    }, {
        min: 801,
        max: 900
    }, {
        min: 901,
        max: 1e3
    }, {
        min: 1001,
        max: 1100
    }, {
        min: 1101,
        max: 1200
    }, {
        min: 1201,
        max: 1300
    }, {
        min: 1301,
        max: 1400
    }, {
        min: 1401,
        max: 1500
    }, {
        min: 1501,
        max: 3e3
    }, {
        min: 3001,
        max: 5e3
    }],
    prices = [{
        type: "anual",
        produto: [{
            produto: "Competências",
            price: [{
                rango: 0,
                price: 134.26
            }, {
                rango: 1,
                price: 89.51
            }, {
                rango: 2,
                price: 84.34
            }, {
                rango: 3,
                price: 79.18
            }, {
                rango: 4,
                price: 70.57
            }, {
                rango: 5,
                price: 61.97
            }, {
                rango: 6,
                price: 57.66
            }, {
                rango: 7,
                price: 53.36
            }, {
                rango: 8,
                price: 49.06
            }, {
                rango: 9,
                price: 44.75
            }, {
                rango: 10,
                price: 43.46
            }, {
                rango: 11,
                price: 42.60
            }, {
                rango: 12,
                price: 41.31
            }, {
                rango: 13,
                price: 40.45
            }, {
                rango: 14,
                price: 39.59
            }, {
                rango: 15,
                price: 38.30
            }, {
                rango: 16,
                price: 37.44
            }, {
                rango: 17,
                price: 36.15
            }, {
                rango: 18,
                price: 35.29
            }, {
                rango: 19,
                price: 34.43
            }, {
                rango: 20,
                price: 30.98
            }, {
                rango: 21,
                price: 24.10
            }]
        }, {
            produto: "Clima",
            price: [{
                rango: 0,
                price: 41.24
            }, {
                rango: 1,
                price: 25.35
            }, {
                rango: 2,
                price: 24.10
            }, {
                rango: 3,
                price: 22.59
            }, {
                rango: 4,
                price: 20.08
            }, {
                rango: 5,
                price: 17.57
            }, {
                rango: 6,
                price: 16.32
            }, {
                rango: 7,
                price: 15.06
            }, {
                rango: 8,
                price: 13.81
            }, {
                rango: 9,
                price: 12.55
            }, {
                rango: 10,
                price: 12.05
            }, {
                rango: 11,
                price: 11.80
            }, {
                rango: 12,
                price: 11.55
          }, {
                rango: 13,
                price: 11.30
          }, {
                rango: 14,
                price: 11.04
          }, {
                rango: 15,
                price: 10.54
          }, {
                rango: 16,
                price: 10.29
          }, {
                rango: 17,
                price: 10.04
          }, {
                rango: 18,
                price: 10.65
          }, {
                rango: 19,
                price: 9.54
          }, {
                rango: 20,
                price: 8.79
          }, {
                rango: 21,
                price: 6.78
          }]
        }, {
            produto: "total",
            price: [{
                rango: 0,
                price: 342.6925656
            }, {
                rango: 1,
                price: 228.4617104
            }, {
                rango: 2,
                price: 212.7910516
            }, {
                rango: 3,
                price: 197.5327785
            }, {
                rango: 4,
                price: 173.6144045
            }, {
                rango: 5,
                price: 149.6960305
            }, {
                rango: 6,
                price: 140.211158
            }, {
                rango: 7,
                price: 131.1386713
            }, {
                rango: 8,
                price: 122.0661846
            }, {
                rango: 9,
                price: 112.9936979
            }, {
                rango: 10,
                price: 110.1069976
            }, {
                rango: 11,
                price: 107.6326831
            }, {
                rango: 12,
                price: 104.7459827
            }, {
                rango: 13,
                price: 102.2716682
            }, {
                rango: 14,
                price: 99.79735364
            }, {
                rango: 15,
                price: 96.91065333
            }, {
                rango: 16,
                price: 94.43633877
            }, {
                rango: 17,
                price: 91.54963846
            }, {
                rango: 18,
                price: 89.07532391
            }, {
                rango: 19,
                price: 86.60100936
            }, {
                rango: 20,
                price: 72.1675078
            }, {
                rango: 21,
                price: 55.67207744
            }]
        }, {
            produto: "Desempenho",
            price: [{
                rango: 0,
                price: 232.37
              }, {
                rango: 1,
                price: 154.91
              }, {
                rango: 2,
                price: 142.86
            }, {
                rango: 3,
                price: 130.82
            }, {
                rango: 4,
                price: 113.60
            }, {
                rango: 5,
                price: 96.39

            }, {
                rango: 6,
                price: 91.23
            }, {
                rango: 7,
                price: 86.06
          }, {
                rango: 8,
                price: 80.90
            }, {
                rango: 9,
                price: 75.74

            }, {
                rango: 10,
                price: 74.01
            }, {
                rango: 11,
                price: 72.29
            }, {
                rango: 12,
                price: 70.57
            }, {
                rango: 13,
                price: 68.85
            }, {
                rango: 14,
                price: 67.13
            }, {
                rango: 15,
                price: 65.41
            }, {
                rango: 16,
                price: 63.69
            }, {
                rango: 17,
                price: 61.97
            }, {
                rango: 18,
                price: 60.24
            }, {
                rango: 19,
                price: 58.52
            }, {
                rango: 20,
                price: 44.75
            }, {
                rango: 21,
                price: 34.43
           }]
        }, {
            produto: "Metas",
            price: [{
                rango: 0,
                price: 134.26
            }, {
                rango: 1,
                price: 89.51
            }, {
                rango: 2,
                price: 84.34
            }, {
                rango: 3,
                price: 79.18
            }, {
                rango: 4,
                price: 70.57
            }, {
                rango: 5,
                price: 61.97
            }, {
                rango: 6,
                price: 57.66
            }, {
                rango: 7,
                price: 53.36
            }, {
                rango: 8,
                price: 49.06
            }, {
                rango: 9,
                price: 44.75
            }, {
                rango: 10,
                price: 43.46
            }, {
                rango: 11,
                price: 42.60
            }, {
                rango: 12,
                price: 41.31
            }, {
                rango: 13,
                price: 40.45
            }, {
                rango: 14,
                price: 39.59
            }, {
                rango: 15,
                price: 38.30
            }, {
                rango: 16,
                price: 37.44
            }, {
                rango: 17,
                price: 36.15
            }, {
                rango: 18,
                price: 35.29
            }, {
                rango: 19,
                price: 34.43
           }, {
                rango: 20,
                price: 30.98
            }, {
                rango: 21,
                price: 24.10
            }]
        }, {
            produto: "PDI",
            price: [{
                rango: 0,
                price: 83.91
            }, {
                rango: 1,
                price: 55.94
            }, {
                rango: 2,
                price: 52.936
            }, {
                rango: 3,
                price: 49.49
            }, {
                rango: 4,
                price: 44.326
            }, {
                rango: 5,
                price: 38.73
            }, {
                rango: 6,
                price: 35.72
            }, {
                rango: 7,
                price: 33.13
            }, {
                rango: 8,
                price: 30.55
            }, {
                rango: 9,
                price: 27.97
              }, {
                rango: 10,
                price: 27.11
            }, {
                rango: 11,
                price: 26.68
            }, {
                rango: 12,
                price: 25.82
              }, {
                rango: 13,
                price: 25.39
            }, {
                rango: 14,
                price: 24.53
            }, {
                rango: 15,
                price: 24.10
            }, {
                rango: 16,
                price: 23.24
            }, {
                rango: 17,
                price: 22.81
            }, {
                rango: 18,
                price: 21.95
            }, {
                rango: 19,
                price: 21.52
              }, {
                rango: 20,
                price: 19.36
              }, {
                rango: 21,
                price: 15.06
            }]
        }, {
            produto: "Medalhas de Mérito",
            price: [{
                rango: 0,
                price: 26.89
            }, {
                rango: 1,
                price: 17.93
              }, {
                rango: 2,
                price: 16.85
            }, {
                rango: 3,
                price: 15.78
            }, {
                rango: 4,
                price: 13.99
            }, {
                rango: 5,
                price: 12.19
            }, {
                rango: 6,
                price: 11.12
            }, {
                rango: 7,
                price: 10.40
            }, {
                rango: 8,
                price: 9.32
            }, {
                rango: 9,
                price: 8.61
            }, {
                rango: 10,
                price: 8.25
            }, {
                rango: 11,
                price: 7.89
            }, {
                rango: 12,
                price: 7.89
            }, {
                rango: 13,
                price: 7.53
            }, {
                rango: 14,
                price: 7.53
            }, {
                rango: 15,
                price: 7.17
           }, {
                rango: 16,
                price: 6.81
            }, {
                rango: 17,
                price: 6.81
            }, {
                rango: 18,
                price: 6.45
            }, {
                rango: 19,
                price: 6.45
            }, {
                rango: 20,
                price: 5.74

            }, {
                rango: 21,
                price: 4.30
            }]
        }, {
            produto: "Clima",
            price: [{
                rango: 0,
                price: 41.24
            }, {
                rango: 1,
                price: 22.59
            }, {
                rango: 2,
                price: 21.59
            }, {
                rango: 3,
                price: 20.33
            }, {
                rango: 4,
                price: 18.07
            }, {
                rango: 5,
                price: 15.81
            }, {
                rango: 6,
                price: 14.56
            }, {
                rango: 7,
                price: 13.55
            }, {
                rango: 8,
                price: 12.30
            }, {
                rango: 9,
                price: 11.30
            }, {
                rango: 10,
                price: 10.79

            }, {
                rango: 11,
                price: 10.54
            }, {
                rango: 12,
                price: 10.29
            }, {
                rango: 13,
                price: 10.04
            }, {
                rango: 14,
                price: 9.79

            }, {
                rango: 15,
                price: 9.54

            }, {
                rango: 16,
                price: 9.29

            }, {
                rango: 17,
                price: 9.04

            }, {
                rango: 18,
                price: 8.79

            }, {
                rango: 19,
                price: 8.53

            }, {
                rango: 20,
                price: 7.78

            }, {
                rango: 21,
                price: 6.02
            }]
        }, {
            produto: "Clima",
            price: [{
                rango: 0,
                price: 27.97
            }, {
                rango: 1,
                price: 18.07
             }, {
                rango: 2,
                price: 17.07
            }, {
                rango: 3,
                price: 16.07
            }, {
                rango: 4,
                price: 14.31
            }, {
                rango: 5,
                price: 12.55
            }, {
                rango: 6,
                price: 11.55
            }, {
                rango: 7,
                price: 10.79
            }, {
                rango: 8,
                price: 9.79

            }, {
                rango: 9,
                price: 9.04

            }, {
                rango: 10,
                price: 8.79

            }, {
                rango: 11,
                price: 8.53

            }, {
                rango: 12,
                price: 8.28

            }, {
                rango: 13,
                price: 8.03

            }, {
                rango: 14,
                price: 7.78

            }, {
                rango: 15,
                price: 7.53

            }, {
                rango: 16,
                price: 7.28
           }, {
                rango: 17,
                price: 7.03
           }, {
                rango: 18,
                price: 6.78

            }, {
                rango: 19,
                price: 6.78

            }, {
                rango: 20,
                price: 6.02

            }, {
                rango: 21,
                price: 4.77
            }]
        }, {
            produto: "desarrollo",
            price: [{
                rango: 0,
                price: 132.16
            }, {
                rango: 1,
                price: 88.11
            }, {
                rango: 2,
                price: 81.38
            }, {
                rango: 3,
                price: 74.40
            }, {
                rango: 4,
                price: 64.73
            }, {
                rango: 5,
                price: 54.82
            }, {
                rango: 6,
                price: 51.71
            }, {
                rango: 7,
                price: 48.83
            }, {
                rango: 8,
                price: 45.95
            }, {
                rango: 9,
                price: 43.07
            }, {
                rango: 10,
                price: 42.06
            }, {
                rango: 11,
                price: 41.15
            }, {
                rango: 12,
                price: 40.14
            }, {
                rango: 13,
                price: 39.22
            }, {
                rango: 14,
                price: 38.05
            }, {
                rango: 15,
                price: 37.30
            }, {
                rango: 16,
                price: 36.13
            }, {
                rango: 17,
                price: 35.37
            }, {
                rango: 18,
                price: 34.20
            }, {
                rango: 19,
                price: 33.28
            }, {
                rango: 20,
                price: 25.45
            }, {
                rango: 21,
                price: 19.58
            }]
        }, {
            produto: "engagement",
            price: [{
                rango: 0,
                price: 85.67
            }, {
                rango: 1,
                price: 57.12
            }, {
                rango: 2,
                price: 53.20
            }, {
                rango: 3,
                price: 49.38
            }, {
                rango: 4,
                price: 43.40
            }, {
                rango: 5,
                price: 37.42
            }, {
                rango: 6,
                price: 35.05
            }, {
                rango: 7,
                price: 32.79
            }, {
                rango: 8,
                price: 30.52
            }, {
                rango: 9,
                price: 28.25
            }, {
                rango: 10,
                price: 27.53
            }, {
                rango: 11,
                price: 26.91
            }, {
                rango: 12,
                price: 26.19
            }, {
                rango: 13,
                price: 25.57
            }, {
                rango: 14,
                price: 24.95
            }, {
                rango: 15,
                price: 24.23
            }, {
                rango: 16,
                price: 23.61
            }, {
                rango: 17,
                price: 22.89
            }, {
                rango: 18,
                price: 22.27
            }, {
                rango: 19,
                price: 21.65
            }, {
                rango: 20,
                price: 18.04
            }, {
                rango: 21,
                price: 13.92
            }]
        }, {
            produto: "Plano de Sucessão",
            price: [{
                rango: 0,
                price: 67.13
            }, {
                rango: 1,
                price: 44.75
            }, {
                rango: 2,
                price: 42.17
            }, {
                rango: 3,
                price: 39.59
            }, {
                rango: 4,
                price: 35.29
            }, {
                rango: 5,
                price: 30.98
            }, {
                rango: 6,
                price: 28.83
            }, {
                rango: 7,
                price: 26.68
            }, {
                rango: 8,
                price: 24.53
            }, {
                rango: 9,
                price: 22.38
            }, {
                rango: 10,
                price: 21.73
            }, {
                rango: 11,
                price: 21.30
            }, {
                rango: 12,
                price: 20.66
            }, {
                rango: 13,
                price: 20.22
            }, {
                rango: 14,
                price: 19.79
            }, {
                rango: 15,
                price: 19.15
            }, {
                rango: 16,
                price: 18.72
            }, {
                rango: 17,
                price: 18.07
            }, {
                rango: 18,
                price: 17.64
            }, {
                rango: 19,
                price: 17.21
            }, {
                rango: 20,
                price: 15.49
            }, {
                rango: 21,
                price: 12.05
            }]
        }]
    }, {
        type: "unico",
        produto: [{
            produto: "Competências",
            price: [{
                rango: 0,
                price: 104.89
            }, {
                rango: 1,
                price: 69.93
            }, {
                rango: 2,
                price: 65.98
            }, {
                rango: 3,
                price: 62.04
            }, {
                rango: 4,
                price: 55.22
            }, {
                rango: 5,
                price: 48.41
            }, {
                rango: 6,
                price: 44.82
            }, {
                rango: 7,
                price: 41.60
            }, {
                rango: 8,
                price: 38.37
            }, {
                rango: 9,
                price: 35.14
            }, {
                rango: 10,
                price: 34.07
            }, {
                rango: 11,
                price: 33.35
            }, {
                rango: 12,
                price: 32.63
            }, {
                rango: 13,
                price: 31.56
            }, {
                rango: 14,
                price: 30.84
            }, {
                rango: 15,
                price: 30.12
            }, {
                rango: 16,
                price: 29.05
            }, {
                rango: 17,
                price: 28.33
            }, {
                rango: 18,
                price: 27.61
            }, {
                rango: 19,
                price: 26.89
            }, {
                rango: 20,
                price: 24.38
            }, {
                rango: 21,
                price: 19.01
            }]
        }, {
            produto: "Clima",
            price: [{
                rango: 0,
                price: 49.84
            }, {
                rango: 1,
                price: 36.65
            }, {
                rango: 2,
                price: 34.39
            }, {
                rango: 3,
                price: 32.38
            }, {
                rango: 4,
                price: 28.87
            }, {
                rango: 5,
                price: 25.35
            }, {
                rango: 6,
                price: 23.60
            }, {
                rango: 7,
                price: 21.84
            }, {
                rango: 8,
                price: 20.08
            }, {
                rango: 9,
                price: 18.32
            }, {
                rango: 10,
                price: 17.82
            }, {
                rango: 11,
                price: 17.32
            }, {
                rango: 12,
                price: 16.82
            }, {
                rango: 13,
                price: 16.57
            }, {
                rango: 14,
                price: 16.07
            }, {
                rango: 15,
                price: 15.56
            }, {
                rango: 16,
                price: 15.31
            }, {
                rango: 17,
                price: 14.81
            }, {
                rango: 18,
                price: 14.31
            }, {
                rango: 19,
                price: 14.06
            }, {
                rango: 20,
                price: 12.80
            }, {
                rango: 21,
                price: 9.79
              }]
        }, {
            produto: "Clima",
            price: [{
                rango: 0,
                price: 52.30
            }, {
                rango: 1,
                price: 32.88
            }, {
                rango: 2,
                price: 30.88
            }, {
                rango: 3,
                price: 29.12
            }, {
                rango: 4,
                price: 25.85
            }, {
                rango: 5,
                price: 22.59
            }, {
                rango: 6,
                price: 20.83
            }, {
                rango: 7,
                price: 19.33
            }, {
                rango: 8,
                price: 17.82
            }, {
                rango: 9,
                price: 16.32
            }, {
                rango: 10,
                price: 15.81
            }, {
                rango: 11,
                price: 15.56
            }, {
                rango: 12,
                price: 15.06
            }, {
                rango: 13,
                price: 14.81
            }, {
                rango: 14,
                price: 14.31
            }, {
                rango: 15,
                price: 14.06
            }, {
                rango: 16,
                price: 13.55
            }, {
                rango: 17,
                price: 13.30
            }, {
                rango: 18,
                price: 12.80
            }, {
                rango: 19,
                price: 12.55
            }, {
                rango: 20,
                price: 11.30
            }, {
                rango: 21,
                price: 8.79
            }]
        }, {
            produto: "Clima",
            price: [{
                rango: 0,
                price: 38.01120908
            }, {
                rango: 1,
                price: 26.10581152
            }, {
                rango: 2,
                price: 24.59970701
            }, {
                rango: 3,
                price: 23.09360249
            }, {
                rango: 4,
                price: 20.58342831
            }, {
                rango: 5,
                price: 18.07325413
            }, {
                rango: 6,
                price: 16.81816703
            }, {
                rango: 7,
                price: 15.56307994
            }, {
                rango: 8,
                price: 14.30799285
            }, {
                rango: 9,
                price: 13.05290576
            }, {
                rango: 10,
                price: 12.55087092
            }, {
                rango: 11,
                price: 12.2998535

            }, {
                rango: 12,
                price: 12.04883608
            }, {
                rango: 13,
                price: 11.79781867
            }, {
                rango: 14,
                price: 11.54680125
            }, {
                rango: 15,
                price: 11.04476641
            }, {
                rango: 16,
                price: 10.79374899
            }, {
                rango: 17,
                price: 10.54273157
            }, {
                rango: 18,
                price: 10.29171416
            }, {
                rango: 19,
                price: 10.04069674
            }, {
                rango: 20,
                price: 9.036627063
            }, {
                rango: 21,
                price: 7.028487716
            }]
        }]
    }];
